### ISSUE TITLE
make run-udocker gives AttributeError: type object '_io.BytesIO' has no attribute 'StringIO' on ManjaroLinux

### ISSUE THREAD

**Issue by HannoSpreeuw** [EOSC-LOFAR/prefactor-cwl#30]
lsb_release -a
--->
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	18.0.0-rc
Codename:	Illyria

git clone git@github.com:EOSC-LOFAR/prefactor-cwl.git          
cd prefactor-cwl
make small
make run-udocker
.....
.....
Info: installing from: http://repo.indigo-datacloud.eu/repository/indigo/2/centos7/x86_64/tgz/udocker-1.1.1.tar.gz
Traceback (most recent call last):
  File "some_path/udocker/prefactor-cwl/.virtualenv/bin/udocker", line 6663, in <module>
    sys.exit(Main().start())
  File "some_path/udocker/prefactor-cwl/.virtualenv/bin/udocker", line 6651, in start
    exit_status = self.execute()
  File "some_path/udocker/prefactor-cwl/.virtualenv/bin/udocker", line 6631, in execute
    cmds["install"](None)
  File "some_path/udocker/prefactor-cwl/.virtualenv/bin/udocker", line 6300, in do_install
    status = utools.install(force)
  File "some_path/udocker/prefactor-cwl/.virtualenv/bin/udocker", line 1265, in install
    tarball_file = self._download(tarball)
  File "some_path/udocker/prefactor-cwl/.virtualenv/bin/udocker", line 1154, in _download
    (hdr, dummy) = self.curl.get(tarball_url, ofile=tarball_file)
  File "some_path/udocker/prefactor-cwl/.virtualenv/bin/udocker", line 4413, in get
    return self._geturl.get(*args, **kwargs)
  File "some_path/udocker/prefactor-cwl/.virtualenv/bin/udocker", line 4501, in get
    buf = cStringIO.StringIO()
AttributeError: type object '_io.BytesIO' has no attribute 'StringIO'
[job ndppp_prep_cal] Job error:
Error collecting output for parameter 'msout':
steps/ndppp_prep_cal.cwl:164:7: Did not find output file with glob pattern: '[u'calibrated.MS']'
[job ndppp_prep_cal] completed permanentFail
Workflow cannot make any more progress.
Final process status is permanentFail
make: *** [Makefile:48: run-udocker] Error 1

**Comment by mr-c** [comment]
Change the first line of `.virtualenv/bin/udocker` to read `python2` instead of plain `python`
or install from the `devel` branch on GitHub:
```
  curl https://raw.githubusercontent.com/indigo-dc/udocker/devel/udocker.py > udocker
  chmod u+rx ./udocker
  ./udocker install
```

**Comment by HannoSpreeuw** [comment]
Thanks. I chose the first option. Fixed.
